apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  app: {{.Name}}
  namespace: {{.Namespace}}
  annotations:
    {{- range $key,$value := .Annotations }}
    {{- if contains $key "ingress.kubernetes.io"}}
    {{$key}}: "{{$value}}"
    {{- end }}
    {{- end }}
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/ssl-redirect: "true"
    ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
  - hosts:
    - {{.Site}}
    secretName: tls-{{.Namespace}}
  rules:
  - host: {{.Site}}
    http:
      paths:
      - path: /api/{{.Name}}
        backend:
          serviceName: {{.Image}}
          servicePort: 80
